baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Lextra hack stuff'
theme = "blowfish"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    #style = 'github-dark'
    style = 'github-dark'

[[main]]
 name = "writeups"
 pageRef = "writeups"
 weight = 10

[[main]]
 name = "about"
 pageRef = "/"
 weight = 20