baseURL = 'https://hexpysya.github.io/bubka/'
languageCode = 'en-us'
title = 'bubka hacks stuff'
theme = "blowfish"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    style = 'github-dark'
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
[[menus.main]]
  name = "writeups"
  pageRef = "writeups"  
  weight = 10

[[menus.main]]
  name = "about"
  pageRef = "/"        
  weight = 20

[params]
colorScheme = "github"
# avocado, fire, ocean, forest, princess, neon, bloody, terminal, marvel, noir, autumn, congo, slate, github, and one-light
defaultAppearance = "one-light" # valid options: light or dark
defaultBackgroundImage = "mountains1.jpg"
highlightCurrentMenuArea = false
smartTOC = true

[params.header]
  layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[params.footer]
  showMenu = true
  showCopyright = false
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[params.homepage]
  layout = "background" 

[params.article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = false
  # showAuthorBottom = false
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = false
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  # showRelatedContent = false
  # relatedContentLimit = 3
  showTaxonomies = true # use showTaxonomies OR showCategoryOnly, not both
  showCategoryOnly = false # use showTaxonomies OR showCategoryOnly, not both
  showAuthorsBadges = true
  showWordCount = false
  # sharingLinks = [ "linkedin", "twitter", "bluesky", "mastodon", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram", "line"]
  showZenMode = false
  # externalLinkForceNewTab = false # disable to allow external links in the same tab (defaults to true)

[params.list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = false
  orderByWeight = false
  groupByYear = true
  cardView = true   # ось це зміни
  cardViewScreenWidth = false
  constrainItemsWidth = false

[params.taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = false